development:
  secret_key_base: c936e897d418a6fcc0f1e0e1c2b84fa0c6fc256ff899db58501d7a46e6cdb97c6a2b2a99389f503d91022b22f6e89aedc84e784f7f6b26786b507032b2d12503
  stripe_publishable_key: pk_test_eRAoyPHYKOW0DSyAILeDMOhI
  stripe_secret_key: sk_test_C464tlZc4rJYMFlAUbmoP930


production:
  stripe_publishable_key: ENV['stripe_publishable_key']
  stripe_secret_key: ENV['stripe_secret_key']
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
